

version: "3.7"
services:

  #youcook database service
  youcook-db:
    image: mysql
    container_name: youcook-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      SERVICE_NAME: youcook-db
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 1s
        timeout: 10s
        retries: 5
    
    volumes:
      - db:/migrations
    networks:
      - yc-backend

  #youcook backend server
  youcook-backend:
    depends_on:
      youcook-db:
        condition: service_healthy
    build:
      dockerfile: Dockerfile
    image: carnivuth/youcook-backend
    container_name: youcook-backend
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./:/var/www
    networks:
      - yc-backend
   
volumes:
  db: 
networks:
  yc-backend:
    driver: bridge
