				insert into INGREDIENTS(name)values('Abaloni');
				insert into INGREDIENTS(name)values('Abbacchio');
				insert into INGREDIENTS(name)values('Aburaage');
				insert into INGREDIENTS(name)values('Acciughe (alici)');
				insert into INGREDIENTS(name)values('Acciughe (alici) dissalate');
				insert into INGREDIENTS(name)values('Acciughe (alici) sott olio');
				insert into INGREDIENTS(name)values('Acciughe (alici) sotto sale');
				insert into INGREDIENTS(name)values('Aceto');
				insert into INGREDIENTS(name)values('Aceto balsamico');
				insert into INGREDIENTS(name)values('Aceto balsamico di Modena IGP');
				insert into INGREDIENTS(name)values('Aceto di mele');
				insert into INGREDIENTS(name)values('Aceto di riso');
				insert into INGREDIENTS(name)values('Aceto di sherry');
				insert into INGREDIENTS(name)values('Aceto di vino bianco');
				insert into INGREDIENTS(name)values('Aceto di vino rosso');
				insert into INGREDIENTS(name)values('Babà al rum');
				insert into INGREDIENTS(name)values('Baccalà');
				insert into INGREDIENTS(name)values('Baccelli di vaniglia');
				insert into INGREDIENTS(name)values('Bacche di alloro (lauro)');
				insert into INGREDIENTS(name)values('Bacche di ginepro');
				insert into INGREDIENTS(name)values('Bacche di goji');
				insert into INGREDIENTS(name)values('Bacche di sanbuco');
				insert into INGREDIENTS(name)values('Bacon');
				insert into INGREDIENTS(name)values('Baguette');
				insert into INGREDIENTS(name)values('Banane');
				insert into INGREDIENTS(name)values('Banane mignon');
				insert into INGREDIENTS(name)values('Barbabietole');
				insert into INGREDIENTS(name)values('Barbo');
				insert into INGREDIENTS(name)values('Barchette di pasta brisée');
				insert into INGREDIENTS(name)values('Barchette di pasta sfoglia');
				insert into INGREDIENTS(name)values('Karkadè');
				insert into INGREDIENTS(name)values('Kashiwa');
				insert into INGREDIENTS(name)values('Katsuobushi');
				insert into INGREDIENTS(name)values('Kecap manis');
				insert into INGREDIENTS(name)values('Kefir');
				insert into INGREDIENTS(name)values('Kezuribushi');
				insert into INGREDIENTS(name)values('Kirsch');
				insert into INGREDIENTS(name)values('Kiwi');
				insert into INGREDIENTS(name)values('Kiwi giallo');
				insert into INGREDIENTS(name)values('Kombucha');
				insert into INGREDIENTS(name)values('Koppert cress');
				insert into INGREDIENTS(name)values('Koya (mava)');
				insert into INGREDIENTS(name)values('Kuzu');
				insert into INGREDIENTS(name)values('Lambrusco');
				insert into INGREDIENTS(name)values('Lampascioni');
				insert into INGREDIENTS(name)values('Lamponi');
				insert into INGREDIENTS(name)values('Lardo');
				insert into INGREDIENTS(name)values('Lardo di Arnad');
				insert into INGREDIENTS(name)values('Lardo di Colonnata');
				insert into INGREDIENTS(name)values('Lasagne all uovo');
				insert into INGREDIENTS(name)values('Lasagne verdi all uovo');
				insert into INGREDIENTS(name)values('Lasagnette fresche');
				insert into INGREDIENTS(name)values('Lasagnette verdi');
				insert into INGREDIENTS(name)values('Latte condensato');
				insert into INGREDIENTS(name)values('Latte di avena');
				insert into INGREDIENTS(name)values('Latte di cocco');
				insert into INGREDIENTS(name)values('Latte di mandorla');
				insert into INGREDIENTS(name)values('Latte di riso');
				insert into INGREDIENTS(name)values('Maccarones');
				insert into INGREDIENTS(name)values('Maccheroncini');
				insert into INGREDIENTS(name)values('Maccheroni');
				insert into INGREDIENTS(name)values('Macis in polvere');
				insert into INGREDIENTS(name)values('Madera');
				insert into INGREDIENTS(name)values('Mafaldine');
				insert into INGREDIENTS(name)values('Maggiorana');
				insert into INGREDIENTS(name)values('Maiale');
				insert into INGREDIENTS(name)values('Maialino da latte');
				insert into INGREDIENTS(name)values('Maionese');
				insert into INGREDIENTS(name)values('Mais');
				insert into INGREDIENTS(name)values('Maltagliati');
				insert into INGREDIENTS(name)values('Malto');
				insert into INGREDIENTS(name)values('Malto tostato');
				insert into INGREDIENTS(name)values('Malvasia');
				insert into INGREDIENTS(name)values('Nachos');
				insert into INGREDIENTS(name)values('Nasturzio');
				insert into INGREDIENTS(name)values('Negroni');
				insert into INGREDIENTS(name)values('Nero di seppia');
				insert into INGREDIENTS(name)values('Nespole');
				insert into INGREDIENTS(name)values('Netetu');
				insert into INGREDIENTS(name)values('Nocciole');
				insert into INGREDIENTS(name)values('Noce di vitello');
				insert into INGREDIENTS(name)values('Noce moscata');
				insert into INGREDIENTS(name)values('Noci');
				insert into INGREDIENTS(name)values('Noci macadamia');
				insert into INGREDIENTS(name)values('Noci pecan');
				insert into INGREDIENTS(name)values('Noodles');
				insert into INGREDIENTS(name)values('Nuditella sotto sale');
				insert into INGREDIENTS(name)values('Nutella');
				insert into INGREDIENTS(name)values('OIio di palma');
				insert into INGREDIENTS(name)values('Oca');
				insert into INGREDIENTS(name)values('Old Tom Gin');
				insert into INGREDIENTS(name)values('Olio di cartamo');
				insert into INGREDIENTS(name)values('Olio di chiodi di garofano');
				insert into INGREDIENTS(name)values('Olio di cocco');
				insert into INGREDIENTS(name)values('Olio di colza');
				insert into INGREDIENTS(name)values('Olio di mandorle');
				insert into INGREDIENTS(name)values('Olio di nocciola');
				insert into INGREDIENTS(name)values('Olio di noci');
				insert into INGREDIENTS(name)values('Olio di palma');
				insert into INGREDIENTS(name)values('Olio di riso');
				insert into INGREDIENTS(name)values('Olio di semi di arachide');
				insert into INGREDIENTS(name)values('Olio di semi di girasole');
				insert into INGREDIENTS(name)values('Olio di semi di lino');
				insert into INGREDIENTS(name)values('Paccheri');
				insert into INGREDIENTS(name)values('Pagello (parago)');
				insert into INGREDIENTS(name)values('Paglia e fieno');
				insert into INGREDIENTS(name)values('Pagro');
				insert into INGREDIENTS(name)values('Palline argentate');
				insert into INGREDIENTS(name)values('Palombacci');
				insert into INGREDIENTS(name)values('Palombo');
				insert into INGREDIENTS(name)values('Pan brioche');
				insert into INGREDIENTS(name)values('Pan di Spagna');
				insert into INGREDIENTS(name)values('Pancake');
				insert into INGREDIENTS(name)values('Pancarrè');
				insert into INGREDIENTS(name)values('Pancetta');
				insert into INGREDIENTS(name)values('Pancetta affumicata');
				insert into INGREDIENTS(name)values('Pandoro');
				insert into INGREDIENTS(name)values('Pane');
				insert into INGREDIENTS(name)values('Quadretti all uovo');
				insert into INGREDIENTS(name)values('Quadrucci all uovo');
				insert into INGREDIENTS(name)values('Quaglie');
				insert into INGREDIENTS(name)values('Quartirolo');
				insert into INGREDIENTS(name)values('Quinoa');
				insert into INGREDIENTS(name)values('Quinoa rossa');
				insert into INGREDIENTS(name)values('Rabarbaro');
				insert into INGREDIENTS(name)values('Radicchio');
				insert into INGREDIENTS(name)values('Rafano');
				insert into INGREDIENTS(name)values('Rafano giapponese');
				insert into INGREDIENTS(name)values('Rafano in polvere');
				insert into INGREDIENTS(name)values('Ragù di capriolo');
				insert into INGREDIENTS(name)values('Ramen');
				insert into INGREDIENTS(name)values('Rana pescatrice (coda di rospo)');
				insert into INGREDIENTS(name)values('Rane');
				insert into INGREDIENTS(name)values('Rape');
				insert into INGREDIENTS(name)values('Ravanelli');
				insert into INGREDIENTS(name)values('Razza');
				insert into INGREDIENTS(name)values('Reale di asino');
				insert into INGREDIENTS(name)values('Red Bull');
				insert into INGREDIENTS(name)values('Reginette');
				insert into INGREDIENTS(name)values('Saba');
				insert into INGREDIENTS(name)values('Sagne');
				insert into INGREDIENTS(name)values('Sagne incannulate');
				insert into INGREDIENTS(name)values('Saké');
				insert into INGREDIENTS(name)values('Salame');
				insert into INGREDIENTS(name)values('Salame tipo Napoli');
				insert into INGREDIENTS(name)values('Salamella');
				insert into INGREDIENTS(name)values('Salamini piccanti');
				insert into INGREDIENTS(name)values('Salamini verzini');
				insert into INGREDIENTS(name)values('Salamoia Sichuan');
				insert into INGREDIENTS(name)values('Salatini stick');
				insert into INGREDIENTS(name)values('Sale');
				insert into INGREDIENTS(name)values('Sale grosso');
				insert into INGREDIENTS(name)values('Salmerino');
				insert into INGREDIENTS(name)values('Salmone');
				insert into INGREDIENTS(name)values('Tabasco');
				insert into INGREDIENTS(name)values('Tacchinella');
				insert into INGREDIENTS(name)values('Tacchino');
				insert into INGREDIENTS(name)values('Taccole');
				insert into INGREDIENTS(name)values('Tacconelli');
				insert into INGREDIENTS(name)values('Tacos');
				insert into INGREDIENTS(name)values('Tagliatelle all uovo');
				insert into INGREDIENTS(name)values('Tagliatelle verdi all uovo');
				insert into INGREDIENTS(name)values('Tagliolini all uovo');
				insert into INGREDIENTS(name)values('Tagliolini verdi all uovo');
				insert into INGREDIENTS(name)values('Tahin (crema di sesamo)');
				insert into INGREDIENTS(name)values('Takuan');
				insert into INGREDIENTS(name)values('Taleggio');
				insert into INGREDIENTS(name)values('Tapenade');
				insert into INGREDIENTS(name)values('Tapioca');
				insert into INGREDIENTS(name)values('Cacao amaro in polvere');
				insert into INGREDIENTS(name)values('Cacao dolce in polvere');
				insert into INGREDIENTS(name)values('Cachaça');
				insert into INGREDIENTS(name)values('Cachi');
				insert into INGREDIENTS(name)values('Caciocavallo');
				insert into INGREDIENTS(name)values('Cacioricotta pugliese');
				insert into INGREDIENTS(name)values('Caciotta');
				insert into INGREDIENTS(name)values('Caffè');
				insert into INGREDIENTS(name)values('Caffè solubile');
				insert into INGREDIENTS(name)values('Cajun');
				insert into INGREDIENTS(name)values('Calamarata');
				insert into INGREDIENTS(name)values('Calamaretti');
				insert into INGREDIENTS(name)values('Calamari');
				insert into INGREDIENTS(name)values('Calvados');
				insert into INGREDIENTS(name)values('Camommo in polvere');
				insert into INGREDIENTS(name)values('Uccelli selvatici');
				insert into INGREDIENTS(name)values('Uccellini');
				insert into INGREDIENTS(name)values('Umeboshi');
				insert into INGREDIENTS(name)values('Uova');
				insert into INGREDIENTS(name)values('Uova di lompo');
				insert into INGREDIENTS(name)values('Uova di quaglia');
				insert into INGREDIENTS(name)values('Uva bianca');
				insert into INGREDIENTS(name)values('Uva fragola');
				insert into INGREDIENTS(name)values('Uva nera');
				insert into INGREDIENTS(name)values('Uva rosa');
				insert into INGREDIENTS(name)values('Uva spina');
				insert into INGREDIENTS(name)values('Uvetta');
				insert into INGREDIENTS(name)values('Uvetta di Corinto');
				insert into INGREDIENTS(name)values('Vaniglia');
				insert into INGREDIENTS(name)values('Vanillina');
				insert into INGREDIENTS(name)values('Veneziane');
				insert into INGREDIENTS(name)values('Ventresca di tonno');
				insert into INGREDIENTS(name)values('Verdure di stagione');
				insert into INGREDIENTS(name)values('Vermicelli');
				insert into INGREDIENTS(name)values('Vermicelli di soia');
				insert into INGREDIENTS(name)values('Vermouth');
				insert into INGREDIENTS(name)values('Vin Santo');
				insert into INGREDIENTS(name)values('Vinaigrette');
				insert into INGREDIENTS(name)values('Vincotto');
				insert into INGREDIENTS(name)values('Vino bianco');
				insert into INGREDIENTS(name)values('Vino passito');
				insert into INGREDIENTS(name)values('Vino rosato');
				insert into INGREDIENTS(name)values('Vino rosso');
				insert into INGREDIENTS(name)values('Wafer al cioccolato');
				insert into INGREDIENTS(name)values('Waffle');
				insert into INGREDIENTS(name)values('Wasabi');
				insert into INGREDIENTS(name)values('Whisky');
				insert into INGREDIENTS(name)values('Wurstel');
				insert into INGREDIENTS(name)values('Xantano');
				insert into INGREDIENTS(name)values('Yogurt');
				insert into INGREDIENTS(name)values('Yogurt di capra');
				insert into INGREDIENTS(name)values('Yogurt greco');
				insert into INGREDIENTS(name)values('Zabaione al marsala');
				insert into INGREDIENTS(name)values('Zafferano');
				insert into INGREDIENTS(name)values('Zafferano in pistilli');
				insert into INGREDIENTS(name)values('Zampone');
				insert into INGREDIENTS(name)values('Zenzero');
				insert into INGREDIENTS(name)values('Zenzero in polvere');
				insert into INGREDIENTS(name)values('Zenzero sciroppato');
				insert into INGREDIENTS(name)values('Zibibbo');
				insert into INGREDIENTS(name)values('Ziti');
				insert into INGREDIENTS(name)values('Zitoni');
				insert into INGREDIENTS(name)values('Zucca');
				insert into INGREDIENTS(name)values('Zucca candita');
				insert into INGREDIENTS(name)values('Zucca delica');
				insert into INGREDIENTS(name)values('Zucca disidratata in polvere');
				insert into INGREDIENTS(name)values('Zucchero');
				insert into INGREDIENTS(name)values('Dado Bimby');
				insert into INGREDIENTS(name)values('Dado ai funghi');
				insert into INGREDIENTS(name)values('Dado di carne');
				insert into INGREDIENTS(name)values('Dado di pollo');
				insert into INGREDIENTS(name)values('Dado vegetale');
				insert into INGREDIENTS(name)values('Daikon');
				insert into INGREDIENTS(name)values('Dashes Peychaud’s bitters');
				insert into INGREDIENTS(name)values('Datteri');
				insert into INGREDIENTS(name)values('Dentice');
				insert into INGREDIENTS(name)values('Distillato di amarene');
				insert into INGREDIENTS(name)values('Distillato di lamponi');
				insert into INGREDIENTS(name)values('Ditali lisci');
				insert into INGREDIENTS(name)values('Ditalini rigati');
				insert into INGREDIENTS(name)values('Ditaloni rigati');
				insert into INGREDIENTS(name)values('Donzella');
				insert into INGREDIENTS(name)values('Edamame');
				insert into INGREDIENTS(name)values('Eglefino');
				insert into INGREDIENTS(name)values('Eglefino affumicato');
				insert into INGREDIENTS(name)values('Eliche');
				insert into INGREDIENTS(name)values('Emmental');
				insert into INGREDIENTS(name)values('Entrecòtes');
				insert into INGREDIENTS(name)values('Erba cipollina');
				insert into INGREDIENTS(name)values('Erba medica');
				insert into INGREDIENTS(name)values('Erbe aromatiche');
				insert into INGREDIENTS(name)values('Eritritolo');
				insert into INGREDIENTS(name)values('Essenza di senape');
				insert into INGREDIENTS(name)values('Estratto di carne');
				insert into INGREDIENTS(name)values('Estratto di mandorle');
				insert into INGREDIENTS(name)values('Estratto di vaniglia');
				insert into INGREDIENTS(name)values('Estratto vegetale');
				insert into INGREDIENTS(name)values('Fagianella');
				insert into INGREDIENTS(name)values('Fagiano');
				insert into INGREDIENTS(name)values('Fagioli azuki');
				insert into INGREDIENTS(name)values('Fagioli bianchi di Spagna');
				insert into INGREDIENTS(name)values('Fagioli borlotti');
				insert into INGREDIENTS(name)values('Fagioli cannellini');
				insert into INGREDIENTS(name)values('Fagioli con l occhio');
				insert into INGREDIENTS(name)values('Fagioli di Sarconi');
				insert into INGREDIENTS(name)values('Fagioli di soia');
				insert into INGREDIENTS(name)values('Fagioli neri');
				insert into INGREDIENTS(name)values('Fagioli rossi');
				insert into INGREDIENTS(name)values('Fagioli toscanelli');
				insert into INGREDIENTS(name)values('Fagioli verdi');
				insert into INGREDIENTS(name)values('Fagiolini');
				insert into INGREDIENTS(name)values('Faraona');
				insert into INGREDIENTS(name)values('Galletto');
				insert into INGREDIENTS(name)values('Gallina');
				insert into INGREDIENTS(name)values('Gallinella');
				insert into INGREDIENTS(name)values('Gamberetti');
				insert into INGREDIENTS(name)values('Gamberi');
				insert into INGREDIENTS(name)values('Gamberi d acqua dolce');
				insert into INGREDIENTS(name)values('Gamberi giganti argentini');
				insert into INGREDIENTS(name)values('Gamberoni');
				insert into INGREDIENTS(name)values('Garam masala');
				insert into INGREDIENTS(name)values('Garganelli all uovo');
				insert into INGREDIENTS(name)values('Gari');
				insert into INGREDIENTS(name)values('Gelatina d agrumi');
				insert into INGREDIENTS(name)values('Gelatina di albicocche');
				insert into INGREDIENTS(name)values('Gelatina di fragole');
				insert into INGREDIENTS(name)values('Gelatina di frutta');
				insert into INGREDIENTS(name)values('Hamburger');
				insert into INGREDIENTS(name)values('Hummus');
				insert into INGREDIENTS(name)values('Impasto per pane');
				insert into INGREDIENTS(name)values('Impasto per pizza');
				insert into INGREDIENTS(name)values('Indivia belga');
				insert into INGREDIENTS(name)values('Indivia scarola');
				insert into INGREDIENTS(name)values('Insalata capricciosa');
				insert into INGREDIENTS(name)values('Insalata mista (misticanza)');
				insert into INGREDIENTS(name)values('Insalata russa');
				insert into INGREDIENTS(name)values('Insaporitore per carni bianche');
				insert into INGREDIENTS(name)values('Insaporitore per pesce');
				insert into INGREDIENTS(name)values('Ippoglosso (halibut)');
				insert into INGREDIENTS(name)values('Irish Whisky');
				insert into INGREDIENTS(name)values('Issopo');
				insert into INGREDIENTS(name)values('Jack Daniels');
				insert into INGREDIENTS(name)values('Jicama')
